name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Test with pytest
      run: |
        pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build
      run: |
        echo CPR_BUILD_VER=$(date +%Y.%m.%d).${{github.run_number}} >> $GITHUB_ENV
        echo $CPR_BUILD_VER
        docker build . --file Dockerfile --build-arg CPR_BUILD_VER=$CPR_BUILD_VER -t kopf/cpr:latest -t kopf/cpr:$CPR_BUILD_VER
    - name: Docker Push
      run: |
        docker push kopf/cpr:$CPR_BUILD_VER
        docker push kopf/cpr:latest
